version: '3.3'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
        - 6060:9090   #控制台端口
        - 9000:9000   #API端口
    volumes:
        - './data:/data'
        - './config:/root/.minio'
    environment:
        MINIO_ROOT_USER: ******
        MINIO_ROOT_PASSWORD: ******
    command: server /data --console-address ':9090'
    restart: always